### ISSUE TITLE
Memory leak detected in version 1.0.6 by veracode

### ISSUE THREAD

**Issue by ccalderon9411** [isaacs/inflight#18]
Veracode has detected a memory leak vulnerability

**Comment by nik750** [comment]
Any update on this vulnarability?

**Comment by nik750** [comment]
**Memory Leak:** inflight is vulnerable to a Memory Leak. The vulnerability is due to lack of restrictions on how many callbacks the library can concurrently support, which can result in a NodeJS out of heap memory crash. 
Still getting this error.

**Comment by Cuttsy27** [comment]
Also wondering if this issue persists? Looks like glob up to glob@9 depends on inflight and other packages in our project depend on glob@<9 so we are stuck with the memory leak warnings in CI

**Comment by krishnamohanparuchuri** [comment]
veracode detected a memory leak vulnerability @1.0.6

**Comment by rennerg** [comment]
Is this repo dead?

**Comment by relaxnow** [comment]
In https://github.com/isaacs/node-glob/issues/435 @isaacs mentioned that newer versions of glob >= 9 no longer use `inflight`.
The remediation for those using older versions of glob would then, presumably be, to upgrade to a newer version.

Sadly, this may not be an option for projects with other transitive dependencies (npmjs.com lists 1628 dependents: https://www.npmjs.com/package/inflight?activeTab=dependents ).
These would all be advised to move away as this library looks to be abandoned.

Unfortunately, in the mean-time applications that transitively use this library would need to determine how they are using this library to determine if they are vulnerable.
Note that the impact of this would be a Denial of Service but would require an attacker to trigger many requests (we were able to reproduce this with millions of simple requests, that may be less in other cases).

It looks like @GreihMurray has been working on using an arbitrary limit of 500 concurrent requests: https://github.com/isaacs/inflight/compare/main...GreihMurray:inflight-fork:main .
This might help but would need to be tested. Also 500 requests may not be enough for some purposes and I'm not sure what happens > 500 requests.

**Comment by 0xSmiley** [comment]
Any update on this?

**Comment by isaacs** [comment]
@0xSmiley No
