### ISSUE TITLE
CWE-772: Missing Release of Resource after Effective Lifetime

### ISSUE THREAD

**Issue by ArtS** [isaacs/inflight#19]
It seems like the most recent version of inflight has a vulnerability https://cwe.mitre.org/data/definitions/772.html

**Comment by patrickcook28** [comment]
The issue I had was `react-query` was using a version of infight that had this vulnerability. The solution for me was to upgrade `"react-query": "3.5.6"`in my package.json

**Comment by yuvaraj-neelagandan** [comment]
What is the solution for this issue ? Anybody any suggestions?

**Comment by KhasanLaudry** [comment]
any update in 2024 to solve this issue?

**Comment by boxexchanger** [comment]
+1 any update ? 
[SNYK-JS-INFLIGHT-6095116](https://security.snyk.io/vuln/SNYK-JS-INFLIGHT-6095116)

**Comment by zhibirc** [comment]
For those who concerned about this issue, this explanation may be be useful: https://github.com/facebook/create-react-app/issues/11174#issue-935928547

**Comment by kovaletsyurii-hue** [comment]
still waiting for updates

**Comment by boxexchanger** [comment]
also.

**Comment by isaacs** [comment]
https://github.com/isaacs/inflight/issues/5#issuecomment-2126153820
