### ISSUE TITLE
[BUG] Vulnerabilities Found in inflight @ 1.0.6

### ISSUE THREAD

**Issue by rmn183** [isaacs/inflight#21]
In NPM inflight there is a Memory Leak because some resources are not freed correctly after being used. It appears to affect all versions, as the issue was not addressed and no fix is found. NOTE: In the meantime, logdna-agent, a package that depends on inflight, has merged a commit to address this solely in their package (so it should be fixed in logdna-agent in versions 1.6.5 and later). Node-glob, a package that also depends on inflight, was also planning to address this by not using inflight after version 8 is released, but it is still being used.

**[react-native @ 0.73.6]**
[@react-native-community/cli-platform-android @ 12.3.6](https://elevance.cxone.cloud/packages/Npm-%40react-native-community%2Fcli-platform-android-12.3.6/packageDetailsGql)
**[glob @ 7.2.3]**
**[inflight @ 1.0.6**]

**Comment by hsharif-rh** [comment]
Any progress on this? I can see various dependancies are showing up as vulnerable due to `inflight`

**Comment by vtulse** [comment]
Team any update on this issues

**Comment by isaacs** [comment]
https://github.com/isaacs/inflight/issues/5#issuecomment-2126153820
