### ISSUE TITLE
Memory leak detected

### ISSUE THREAD

**Issue by jkomyno** [isaacs/inflight#5]
Preliminary note. I didn't installed inflight directly, it's just a package that [glob](https://github.com/isaacs/node-glob) uses.

```
$ npm list inflight
myLibrary@0.0.1 path/to/myLibrary
`-- glob@7.1.2
  `-- inflight@1.0.6
```

I'm developing a CLI apps that scans a set of files in the user's disk. Sometimes, it stops working throwing the following log:

```
<--- Last few GCs --->

[7828:000001CAE9906BF0]      729 ms: Mark-sweep 27.1 (94.3) -> [...] allocation failure GC in old space requested
[7828:000001CAE9906BF0]      754 ms: Mark-sweep 27.1 (94.3) -> [...]  last resort
[7828:000001CAE9906BF0]      780 ms: Mark-sweep 27.1 (32.3) -> [...] last resort


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 000002CEAE928799 <JSObject>
    1: _readdirEntries [path\to\myLibrary\node_modules\glob\glob.js:~559] [pc=000002F43C32198C](this=0000001978260B49 <Glob map = 000000777A7EB871>,abs=0000027C3514ED71 [...]

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
```

So, I've inspected the Node's process' heap usage (node --inspect myLibrary.js) and got the following result, in which the **inflight** module is the most expensive package in terms of retained size.

![memory leak](https://user-images.githubusercontent.com/12381818/33765635-19da6882-dc1a-11e7-9b9a-48e9dc44441c.JPG)

**Comment by Good-man** [comment]
Is this still an issue?  I see that a fix was merged but the issue is still open.

**Comment by tysoncadenhead** [comment]
Can this issue be closed if it's been merged? I'd love to get the warning out of our security scanner

**Comment by relaxnow** [comment]
As far as I can see this was not fixed.

Maybe @Good-man saw https://github.com/isaacs/inflight/issues/5#ref-pullrequest-574816991 and thought it meant a fix was applied?

**Comment by skruzlik** [comment]
Any chance to have this fixed? This package is used all over the place, so it is getting highlighted as a vulnerability almost constantly.

**Comment by ak-seek** [comment]
We are getting Snyk high issues reported due to this memory leak: https://security.snyk.io/vuln/SNYK-JS-INFLIGHT-6095116

**Comment by JasoonX** [comment]
In our project, we resolved this issue by introducing a pre-installation step that utilizes 'npm-force-resolutions'. 
This approach was complemented by adding 'glob' to the 'resolutions' section within our 'package.json'. 
This modification effectively enforces the use of a newer version of 'glob'.
```
package.json

{
...
  "scripts": {
...
    "preinstall": "npx npm-force-resolutions",
  },
  "resolutions": {
    "glob": "10.3.10"
  }
  ...
}

```

**Comment by thetumper** [comment]
Issue and PR in help-me, which resolves transitive issue in pino-pretty:

https://github.com/mcollina/help-me/issues/17
https://github.com/mcollina/help-me/pull/18

Please give a thumbs up there, to help get some priority on it.

**Comment by IdanAdar** [comment]
Snyk at it again. 🙄

**Comment by rreeves8** [comment]
> Considering the issue has been open 6 years and the `inflight.js` file has not been edited in 7 years, I think it's likely this isn't going to be addressed here. If your situation is like mine, you are here because Snyk started complaining about this yesterday (why only yesterday? Who knows...) and a package you depend on depends on this package or, more likely, a package you depend on depends on `glob` which at one point in time depended on `inflight`. The actively-maintained `glob` package [no](https://github.com/isaacs/node-glob/issues/545) [longer](https://github.com/isaacs/node-glob/issues/540) [depends](https://github.com/isaacs/node-glob/issues/487) [on](https://github.com/isaacs/node-glob/issues/435) `inflight`, so your best bet is to (a) pin your `glob` version to something greater than v9, (b) to (respectfully) bug package maintainers to upgrade their `glob` dependency version string, or (c) to ignore the issue because it's probably not doing you real harm anyway. For myself, it's option (c).

I think as nice as it would be to just ignore the issue, a lot of companies require snyk to pass with flying colors. So simply ignoring the issue isn't always the easiest fix. This now effects packages as big as eslint, and I think it needs to be resolved.

**Comment by adominguezepiuse** [comment]
I've been following this issue, and I can see that it has been open for a considerable amount of time. I understand that addressing memory leak issues can be complex and time-consuming.

I was wondering if there has been any recent progress in resolving this problem. Is there any update or new information that can be shared? I'm interested in staying informed about the current status of the situation.

If there are specific steps to reproduce the problem or any additional information that could help, I'd appreciate the details.

**Comment by rreeves8** [comment]
> I've been following this issue, and I can see that it has been open for a considerable amount of time. I understand that addressing memory leak issues can be complex and time-consuming.
> 
> 
> 
> I was wondering if there has been any recent progress in resolving this problem. Is there any update or new information that can be shared? I'm interested in staying informed about the current status of the situation.
> 
> 
> 
> If there are specific steps to reproduce the problem or any additional information that could help, I'd appreciate the details.

From my understanding the biggest problem is glob version 4 uses this package. Which in turn effects a large number of packages. However glob version 10 no longer uses inflight. So it's just a matter of encouraging package maintainers to update there dependencies to resolve it.

**Comment by ramdaniAli** [comment]
While using npm-force-resolutions is a workaround, it doesn't fundamentally resolve the issue since running npm ls glob may still show that the old, vulnerable version of the glob package is present in your dependency tree. A more robust solution is to leverage the overrides feature in your package.json. By explicitly specifying an override for glob, like this:

```
{
  ...
  "overrides": {
    "glob": "10.3.10"
  },
  ...
}

```

You ensure that the specified version of glob is applied throughout your project. However, for this approach to take effect, you will need to perform a fresh installation, you should delete the node_modules folder and the package-lock.json file, and then run npm install. This process forces npm to reinstall all dependencies, taking into account the override you've specified for glob. After doing this, Snyk should no longer report any warnings related to glob, confirming that the chosen version is now in use without any remnants of the old version.

**Comment by rreeves8** [comment]
> using npm-force-resolutions doesn't fundamentally resolve the issue since running npm ls glob may still show that the old, vulnerable version of the glob package is present in your dependency tree. A more robust solution is to leverage the overrides feature in your package.json. By explicitly specifying an override for glob, like this:
> 
> 
> 
> ```
> 
> {
> 
>   ...
> 
>   "overrides": {
> 
>     "glob": "10.3.10"
> 
>   },
> 
>   ...
> 
> }
> 
> 
> 
> ```
> 
> 
> 
> You ensure that the specified version of glob is applied throughout your project. However, for this approach to take effect, you will need to perform a fresh installation, you should delete the node_modules folder and the package-lock.json file, and then run npm install. This process forces npm to reinstall all dependencies, taking into account the override you've specified for glob. After doing this, Snyk should no longer report any warnings related to glob, confirming that the chosen version is now in use without any remnants of the old version.

This isn't a robust solution either. Overriding dependency versions can create instability. Each package version is not exactly the same and changing it for every use case will certainly result in bugs for a project large enough

**Comment by ramdaniAli** [comment]
Certainly, overriding a sub dependency versions carries inherent risks, such as the introduction of unpredictable behavior or a destabilization of system components. Despite these concerns, in my specific situation where glob functions solely as a dependent of argon2, the associated risks are somewhat contained and manageable. At present, our most prudent course of action would be to remain vigilant for updates issued by the argon2 maintainers, in the hope that they will provide a comprehensive solution to the dependency concern.

**Comment by davidguilherme** [comment]
Glob package has a breaking change from version 8.x (latest with inflight) to 9.x (first without it). [They changed its API to use promises instead of callbacks](https://github.com/isaacs/node-glob/blob/v9.0.0/changelog.md). I believe the best approach is to patch 8.x version to stop using inflight which will make a lot easier to override it in the package.json.

**Comment by MandeeGit** [comment]
we are seeing the same issue in checkmarx as well. is this false positive?

CWE-772

![image](https://github.com/isaacs/inflight/assets/161084607/e054e34b-ae2f-4a64-98ae-1c0e5e60425c)

**Comment by bholmesACR** [comment]
Any status on a potential fix for this vulnerable package? We dont understand why there hasn't been a fix deployed for this risk yet. Please update us!

**Comment by kburns-r7** [comment]
> Any status on a potential fix for this vulnerable package? We dont understand why there hasn't been a fix deployed for this risk yet. Please update us!

@bholmesACR last commit to this repo was 2 years ago. It seems to have been abandoned.

**Comment by isaacs** [comment]
I have no intention of working on this. I don't use it in or recommend it, and life is too short.

I just deprecated it, and I'll archive this repo shortly.

The language provides a lot of options nowadays for managing promises, which are a much better approach than callbacks in this sort of situation. If you want something that will coalesce async actions for the same key, then the `lru-cache` module provides this in a much more comprehensive way, using the `fetchMethod` function.
